# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88f48d6e9df9dbef3e418fe79b91a867ef9f8475b6acce8986e74aae5c40e76a10cc3cf52fc379d9b5af95717e5df90e2537ff28b30fad34ab58164a385f357f

test:
  secret_key_base: dda23bbb44bd4753b1549dc13ab557b0aabbf5b42d6f221f3130208b95e7b5dfcd4e345e64ab2d5c51e92d2b987d8a9780a7aea12407909def0a98527d91576f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
